# Generated by Django 3.2.3 on 2021-07-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecto',
            old_name='Actualizacion',
            new_name='actualizacion',
        ),
    ]
