# Generated by Django 3.2.5 on 2021-07-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostal', '0002_rename_actualizacion_projecto_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='imagen',
            field=models.ImageField(upload_to='proyecto'),
        ),
    ]
