# Generated by Django 3.2.5 on 2021-07-08 22:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostal', '0003_auto_20210706_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Comedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.TextField(max_length=150, unique=True)),
                ('rubro', models.TextField(max_length=150, unique=True)),
                ('nombre_empresa', models.CharField(max_length=150, unique=True)),
                ('contacto', models.CharField(max_length=150, unique=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro', models.CharField(max_length=150, unique=True)),
                ('rut', models.CharField(max_length=150, unique=True)),
                ('medio_pago', models.CharField(max_length=150, unique=True)),
                ('detalle', models.CharField(max_length=150, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=150, unique=True)),
                ('valor_habitacion', models.PositiveIntegerField(default=0)),
                ('cantidad_camas', models.PositiveIntegerField(default=0)),
                ('refrescos', models.CharField(max_length=300, unique=True)),
                ('oficina', models.BooleanField(default=True)),
                ('accesorios', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=150, unique=True)),
                ('tipo_menu', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('minuta_diaria', models.CharField(max_length=150, unique=True)),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('telefono', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=150, unique=True)),
                ('mediodepago', models.CharField(max_length=150, unique=True)),
                ('nombre_e', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.empresa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.solicitante')),
            ],
            options={
                'verbose_name_plural': 'Ordenes Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('contacto', models.CharField(max_length=150, unique=True, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=150, unique=True, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=150, unique=True, verbose_name='Direccion')),
                ('Solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.solicitante', verbose_name='Solicitante')),
                ('comedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.comedor')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.habitacion')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.menu', verbose_name='Menu')),
            ],
            options={
                'verbose_name_plural': 'Huespedes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.menu'),
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('Factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.factura')),
                ('huesped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.huesped')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hostal.orden_compra')),
            ],
            options={
                'verbose_name_plural': 'Detalles Ventas',
                'ordering': ['id'],
            },
        ),
    ]
