# Generated by Django 3.2.5 on 2021-07-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostal', '0004_auto_20210708_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default=2, upload_to='proyecto'),
            preserve_default=False,
        ),
    ]
