# Generated by Django 3.2.5 on 2021-07-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20210708_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombreEmpresa',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
